### ISSUE TITLE
Not able to find connection Strings in atlasBasic Construct

### ISSUE THREAD

**Issue by dahiyahimanshu** [mongodb/awscdk-resources-mongodbatlas#26]
For testing connection and proving IP access list, i started with AtlasBasic construct.

```

from aws_cdk import (
    Stack, CfnOutput
)
from constructs import Construct

from awscdk_resources_mongodbatlas import (AdvancedRegionConfig, AdvancedReplicationSpec,
                                           Specs, AccessListDefinition, IpAccessListProps,
                                           ProjectProps, ClusterProps, AtlasBasic, PrivateEndpoint,
                                           AtlasBasicPrivateEndpoint, AtlasBasicProps, PrivateEndpointProps)


class MongodbStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        org_id_var = self.node.try_get_context('org_id')
        region_var = self.node.try_get_context('region')
        profile_name_var = self.node.try_get_context('profile')
        ip_addr_var = self.node.try_get_context('ip_addr')
        ip_comment_var = self.node.try_get_context('ip_comment')
        # vpc_id = self.node.try_get_context('vpc_id')
        # subnets = self.node.try_get_context('subnets')

        region_configs_var = [
            AdvancedRegionConfig(analytics_specs=Specs(node_count=1, instance_size="M10", ebs_volume_type="STANDARD"),
                                 electable_specs=Specs(node_count=3, instance_size="M10", ebs_volume_type="STANDARD"),
                                 priority=7,
                                 region_name=region_var)]
        replication_specs_var = [AdvancedReplicationSpec(advanced_region_configs=region_configs_var, num_shards=1)]

        access_list_defs_var = [AccessListDefinition(ip_address=ip_addr_var, comment=ip_comment_var)]

        atlas_basic_l3 = AtlasBasic(self, "AtlasBasic-py-l3",
                                    cluster_props=ClusterProps(replication_specs=replication_specs_var),
                                    project_props=ProjectProps(org_id=org_id_var),
                                    ip_access_list_props=IpAccessListProps(access_list=access_list_defs_var),
                                    profile=profile_name_var)
        print(atlas_basic_l3.m_cluster.props)
        CfnOutput(self,
                  f"stdUrl",
                  description=f"URL of mongoDb url",
                  value=atlas_basic_l3.m_cluster.props.connection_strings.standard)
        CfnOutput(self,
                  f"stdSrvUrl",
                  description=f"Srv URL of mongoDb url",
                  value=atlas_basic_l3.m_cluster.props.connection_strings.standard_srv)

```

I followed new repo, i am not able to CfnOutput connection parameters. Getting Below problem. Please help.

```
(.venv) hdahiya@IN-HDAHIYA-T14:~/mongodb4$ cdk deploy --context org_id=640dba22c5b1cc609ab132d0 --context region=EU_WEST_1 --context profile=mycom-default --context ip_addr='103.65.30.238'
CfnClusterProps(name='atlas-cluster-9883149', project_id='${Token[TOKEN.651]}', cluster_type='REPLICASET', profile='mycom-default', replication_specs=[AdvancedReplicationSpec(advanced_region_configs=[AdvancedRegionConfig(analytics_specs=Specs(ebs_volume_type='STANDARD', instance_size='M10', node_count=1), electable_specs=Specs(ebs_volume_type='STANDARD', instance_size='M10', node_count=3), priority=7, region_name='EU_WEST_1')], num_shards=1)])
Traceback (most recent call last):
  File "/home/hdahiya/mongodb4/app.py", line 10, in <module>
    MongodbStack(app, "MongodbStack",
  File "/home/hdahiya/mongodb4/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/hdahiya/mongodb4/mongodb/mongodb_stack.py", line 43, in __init__
    value=atlas_basic_l3.m_cluster.props.connection_strings.standard)
AttributeError: 'NoneType' object has no attribute 'standard'

Subprocess exited with error 1
```

**Comment by andreaangiolillo** [comment]
Hello 👋 ,

We have released v1.0.1 with the fix to this issue. Please, make sure to download this new version to your CDK project.

```bash
npm i awscdk-resources-mongodbatlas@latest
```

Once you installed the new version, you will be able to access the cluster's connection strings as follows:

```ts
const clusterRes = new atlas.CfnCluster(this, 'ClusterResource', {............}

new cdk.CfnOutput(this, 'standardSrv', { value: clusterRes.connectionStrings?.standardSrv ?? 'undefined' });
```

Note that the property`connectionStrings` is attached to the constructor itself and not to `clusterRes.props`.

Let me know if this new version fixes your issue.

Thanks!

**Comment by andreaangiolillo** [comment]
Hello 👋 
yes, it is the same. See https://pypi.org/project/awscdk-resources-mongodbatlas/

Thanks

**Comment by andreaangiolillo** [comment]
Hello @dahiyahimanshu,
Any update on this issue? Did you tried v1.0.1?
Thanks

**Comment by dahiyahimanshu** [comment]
Hi @andreaangiolillo ,

I tried with v1.0.1 it is still not working for me. The example provided by you is for CfnCluster whereas i am using l3 construct AtlasBasicPrivateEndpoint from which the connection_strings are coming as None.

**Comment by andreaangiolillo** [comment]
Hello @dahiyahimanshu,

you should be able to access the access string with AtlasBasicPrivateEndpoint as follows:

```ts
const atlasPrivateEndpoint = new atlas.AtlasBasicPrivateEndpoint(this, 'PpdMongoDbPrivateEndpoint', {...});

new cdk.CfnOutput(this, 'standardSrv', { value: atlasPrivateEndpoint.atlasBasic.mCluster.connectionStrings?.standardSrv ?? 'undefined' });
```
Let me know if you manage to access the access string in this way.
Thanks

**Comment by dahiyahimanshu** [comment]
Hi @andreaangiolillo ,

i think i would require some private link url if i correlate with mong web UI. There is standard and there is private endpoint url. 
```

  instance = AtlasBasicPrivateEndpoint(self, "AtlasBasic-private-endpoint-py",
                                             atlas_basic_props=atlas_basic_props,
                                             private_endpoint_props=private_endpoint_props,
                                             profile=profile_name_var,
                                             region=region
                                             )
        CfnOutput(self, "mongo-cluster-name", value=instance.atlas_basic.m_cluster.props.name)
        CfnOutput(self, "mongo-private-url", value=instance.atlas_basic.m_cluster.connection_strings.private_endpoint)
        CfnOutput(self, "mongo-private-srv-url", value=instance.atlas_basic.m_cluster.connection_strings.aws_private_link_srv)
        CfnOutput(self, "mongo-std-url", value=instance.atlas_basic.m_cluster.connection_strings.standard)
        CfnOutput(self, "mongo-std-srv-url", value=instance.atlas_basic.m_cluster.connection_strings.standard_srv)
```

**Comment by andreaangiolillo** [comment]
Hello,
I am glad I was able to help you 😄 

>  am confused where should we use aws_private_link_srv or private_endpoint and why it is still None?

You should be able to use **private** & **privateSrv** with VPC peering and **awsPrivateLink** & **awsPrivateLinkSrv** with private endpoint. You should use **privateEndpoint** if you have multiple private endpoints that you can use to connect to your clusters.

Keep in mind that the status of the  AWS PrivateLink connection  must be **available** in order to use **awsPrivateLink** & **awsPrivateLinkSrv** (see [Troubleshoot Private Endpoint Connection Issues](https://www.mongodb.com/docs/atlas/security-private-endpoint/#troubleshoot-private-endpoint-connection-issues))




**awsPrivateLink:**
Private endpoint-aware connection strings that use AWS-hosted clusters with Amazon Web Services (AWS) PrivateLink. Each key identifies an Amazon Web Services (AWS) interface endpoint. Each value identifies the related mongodb:// connection string that you use to connect to MongoDB Cloud through the interface endpoint that the key names.
[Network Peering Connection](https://docs.atlas.mongodb.com/security-vpc-peering/#std-label-vpc-peering/)

**awsPrivateLinkSrv:**
Private endpoint-aware connection strings that use AWS-hosted clusters with Amazon Web Services (AWS) PrivateLink. Each key identifies an Amazon Web Services (AWS) interface endpoint. Each value identifies the related mongodb:// connection string that you use to connect to Atlas through the interface endpoint that the key names.
[Network Peering Connection](https://docs.atlas.mongodb.com/security-vpc-peering/#std-label-vpc-peering/)

**private:**
Network peering connection strings for each interface Virtual Private Cloud (VPC) endpoint that you configured to connect to this cluster. This connection string uses the mongodb+srv:// protocol. The resource returns this parameter once someone creates a network peering connection to this cluster. This protocol tells the application to look up the host seed list in the Domain Name System (DNS). This list synchronizes with the nodes in a cluster. If the connection string uses this Uniform Resource Identifier (URI) format, you don't need to append the seed list or change the URI if the nodes change. Use this URI format if your driver supports it. If it doesn't, use connectionStrings.private. For Amazon Web Services (AWS) clusters, this resource returns this parameter only if you enable custom DNS.
[Network Peering Connection](https://docs.atlas.mongodb.com/security-vpc-peering/#std-label-vpc-peering/)

**privateEndpoint:**
List of private endpoint-aware connection strings that you can use to connect to this cluster through a private endpoint. This parameter returns only if you deployed a private endpoint to all regions to which you deployed this clusters' nodes.

**privateSrv:**
Network peering connection strings for each interface Virtual Private Cloud (VPC) endpoint that you configured to connect to this cluster. This connection string uses the mongodb+srv:// protocol. The resource returns this parameter when someone creates a network peering connection to this cluster. This protocol tells the application to look up the host seed list in the Domain Name System (DNS). This list synchronizes with the nodes in a cluster. If the connection string uses this Uniform Resource Identifier (URI) format, you don't need to append the seed list or change the Uniform Resource Identifier (URI) if the nodes change. Use this Uniform Resource Identifier (URI) format if your driver supports it. If it doesn't, use connectionStrings.private. For Amazon Web Services (AWS) clusters, this parameter returns only if you [enable custom DNS](https://docs.atlas.mongodb.com/reference/api/aws-custom-dns-update/).
[Network Peering Connection](https://docs.atlas.mongodb.com/security-vpc-peering/#std-label-vpc-peering/)

**Comment by dahiyahimanshu** [comment]
Hi after going the text and link. I think if i am setting up **AtlasBasicPrivateEndpoint** i should get awsPrivateLinkSrv or awsPrivateLink values. still getting error when i try to CFNOutput them pls help.

```

Traceback (most recent call last):
  File "/home/hdahiya/aiops-bda-mongo-db/docker/cdk/app.py", line 30, in <module>
    mongodb_stack = MongodbStack(app, ctx_name("MongodbStack"),
  File "/home/hdahiya/aiops-bda-mongo-db/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/hdahiya/aiops-bda-mongo-db/docker/cdk/mongodb/mongodb_stack.py", line 74, in __init__
    CfnOutput(self, "mongo-private-url",
  File "/home/hdahiya/aiops-bda-mongo-db/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/hdahiya/aiops-bda-mongo-db/.venv/lib/python3.10/site-packages/aws_cdk/__init__.py", line 5729, in __init__
    props = CfnOutputProps(
  File "/home/hdahiya/aiops-bda-mongo-db/.venv/lib/python3.10/site-packages/aws_cdk/__init__.py", line 5892, in __init__
    check_type(argname="argument value", value=value, expected_type=type_hints["value"])
  File "/home/hdahiya/aiops-bda-mongo-db/.venv/lib/python3.10/site-packages/typeguard/__init__.py", line 785, in check_type
    raise TypeError(
TypeError: type of argument value must be str; got NoneType instead
```

**Comment by andreaangiolillo** [comment]
Hello 👋 

Could you try to deploy your infrastructure with CDK and then retrieve the cluster connection string with [AtlasCLI](https://www.mongodb.com/docs/atlas/atlas-cli/)? You can get your cluster connection strings by running `atlas cluster connectionstrings get [ClusterName] -o json` .

```
atlas cluster connectionstrings get Cluster94215 -o json                                                                                                                                          
{
  "standard": "mongodb://cluster94215-shard-00-00.vza0k.mongodb-dev.net:27017,cluster94215-shard-00-01.vza0k.mongodb-dev.net:27017,cluster94215-shard-00-02.vza0k.mongodb-dev.net:27017/?ssl=true\u0026authSource=admin\u0026replicaSet=atlas-u8bg8w-shard-0",
  "standardSrv": "mongodb+srv://cluster94215.vza0k.mongodb-dev.net"
}
```
If you get only the standard connection strings it means that you haven't set up the private endpoint correctly. 

Keep in mind that using `AtlasBasicPrivateEndpoint` is not enough to fully configure a private endpoint as there are steps to perform within AWS environment:

-  [Create the interface endpoint in AWS.](https://www.mongodb.com/docs/atlas/security-cluster-private-endpoint/#create-the-interface-endpoint-in-aws)
- [Configure your resources' security groups to send traffic to and receive traffic from the interface endpoint](https://www.mongodb.com/docs/atlas/security-cluster-private-endpoint/#configure-your-resources-security-groups-to-send-traffic-to-and-receive-traffic-from-the)
- [Create a security group for your interface endpoint to allow resources to access it.](https://www.mongodb.com/docs/atlas/security-cluster-private-endpoint/#create-a-security-group-for-your-interface-endpoint-to-allow-resources-to-access-it)

You can check out the AWS documentation to see how to perform those steps with their CDK constructors.
Thanks

**Comment by dahiyahimanshu** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5242576/234570931-5d5410f9-4c59-45c8-bd33-33153ba25dfe.png">
I am able to retrieve through atlas cli related url. how to do it through cfn output pls
